services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../dome-saas/nginx.conf:/etc/nginx/nginx.conf
      - ../dome-saas/certs:/etc/nginx/certs
      - ../dome-saas/html:/usr/share/nginx/html