services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
      - ./html:/usr/share/nginx/html

  issuer-keycloak:
    image: in2workspace/issuer-keycloak-plugin:v1.1.0-SNAPSHOT
    volumes:
      - ./imports:/opt/keycloak/data/import
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_URL: http://localhost:8081
      KC_HOSTNAME_ADMIN_URL: http://localhost:8081
      KC_DB: postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-postgres/cred
      DB_PORT: 5432
#      KC_INTERNAL_URL: http://issuer-keycloak:8080
#      KC_EXTERNAL_URL: http://localhost:8081
      ISSUER_API_URL: http://issuer-api:8080
      PRE_AUTH_LIFESPAN: 10 # required?
      PRE_AUTH_LIFESPAN_TIME_UNIT: MINUTES # required?
      TX_CODE_SIZE: 4 # required?
      TX_CODE_DESCRIPTION: Enter the PIN code # required?
      TOKEN_EXPIRATION: 2592000 # required?
    ports:
      - "8081:8080"

  keycloak-postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: cred
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  issuer-ui:
    image: in2workspace/credential-issuer-ui:v1.1.0-SNAPSHOT
    ports:
      - "4201:8088" # 8088?

  issuer-api:
    image: in2workspace/issuer-api:v0.6.0-SNAPSHOT
    environment:
      SPRING_ACTIVE_PROFILES: default
      SPRING_R2DBC_URL: r2dbc:postgresql://issuer-postgres:5432/issuer
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: postgres
      SPRING_FLYWAY_URL: jdbc:postgresql://issuer-postgres:5432/issuer
      SPRING_MAIL_HOST: host.docker.internal
      SPRING_MAIL_PORT: 1025
      API_EXTERNAL_DOMAIN: http://localhost:8082
      API_INTERNAL_DOMAIN: http://issuer-api:8080
      API_CONFIG_SOURCE: yaml
      API_CACHE_LIFETIME_CREDENTIAL_OFFER: 10
      API_CACHE_LIFETIME_VERIFIABLE_CREDENTIAL: 10
      AUTH_SERVER_PROVIDER: keycloak
      AUTH_SERVER_EXTERNAL_DOMAIN: http://localhost:8081
      AUTH_SERVER_INTERNAL_DOMAIN: http://issuer-keycloak:8080
      AUTH_SERVER_REALM: CredentialIssuer
    ports:
      - "8082:8071"

  issuer-postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: issuer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data2

  # Aquí el Wallet

volumes:
  postgres_data: