services:

  # INFRASTRUCTURE
  ganache:
    image: trufflesuite/ganache-cli:latest
    command:
      - "-l"
      - "800000"
      - "--account"
      - '0x041de193683f117a4b0f0b94f8e3e98d9dcf233010a538c6662c41a18188e038,100000000000000000000'
      - "--account"
      - '0x304d170fb355df65cc17ef7934404fe9baee73a1244380076436dec6fafb1e1f,100000000000000000000'
      - "--account"
      - '0x09bac90daf84adc6ca0e3161e3a67c80e4a2ab79d7f55bf9b82f566e6d62ad87,100000000000000000000'
    ports:
      - "8545:8545"

  contract-create:
    image: quay.io/digitelts/dome-contract-deploy:1.0.0
    environment:
      PRIVATE_KEY: 0x304d170fb355df65cc17ef7934404fe9baee73a1244380076436dec6fafb1e1f
      NODE_ENDPOINT: http://ganache:8545/
      T_NET_CHAIN_ID: 83584648538
      B_NET_CHAIN_ID: 2020
    restart: on-failure
    depends_on:
      - ganache

  # ACCESS NODE A

  scorpio-node-a:
    image: scorpiobroker/all-in-one-runner:java-latest
    environment:
      DBHOST: postgis-node-a
    ports:
      - "9090:9090"
    links:
      - postgis-node-a

  postgis-node-a:
    image: postgis/postgis
    ports:
      - "5432"
    environment:
      POSTGRES_USER: ngb
      POSTGRES_PASSWORD: ngb
      POSTGRES_DB: ngb

  desmos-node-a:
    image: desmos-api:latest
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres-node-a:5432/dbtest
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: postgres
      SPRING_FLYWAY_URL: jdbc:postgresql://postgres-node-a:5432/dbtest
      LOGGING_LEVEL_ES_IN2_DESMOS: DEBUG
      CLIENT_ORGANIZATIONID: VATES-S9999999E
      DLT_ADAPTER_PROVIDER: digitelts
      DLT_ADAPTER_INTERNAL_DOMAIN: http://dlt-adapter-node-a:8080
      DLT_ADAPTER_EXTERNAL_DOMAIN: http://dlt-adapter-node-a:8080
      TX_SUBSCRIPTION_NOTIFICATION_ENDPOINT: http://desmos-node-a:8080/api/v1/notifications/dlt
      TX_SUBSCRIPTION_ENTITY_TYPES: ProductOffering,Category,Catalogue
      BROKER_PROVIDER: scorpio
      BROKER_INTERNAL_DOMAIN: http://scorpio-node-a:9090
      BROKER_EXTERNAL_DOMAIN: http://scorpio-node-a:9090
      NGSI_SUBSCRIPTION_NOTIFICATION_ENDPOINT: http://desmos-node-a:8080/api/v1/notifications/broker
      NGSI_SUBSCRIPTION_ENTITY_TYPES: ProductOffering,Category,Catalogue
    ports:
      - "9092:8080"
    depends_on:
      - dlt-adapter-node-a
      - scorpio-node-a
      - postgres-node-a

  postgres-node-a:
    image: postgres:16.1
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: dbtest

  dlt-adapter-node-a:
    image: quay.io/digitelts/dlt-adapter:1.4-SNAPSHOT
    environment:
      PRIVATE_KEY: 0x304d170fb355df65cc17ef7934404fe9baee73a1244380076436dec6fafb1e1f
      DOME_EVENTS_CONTRACT_ADDRESS:
      RPC_ADDRESS: http://ganache:8545
      DOME_PRODUCTION_BLOCK_NUMBER: 0
      ISS: 0x9eb763b0a6b7e617d56b85f1df943f176018c8eedb2dd9dd37c0bd77496833fe
    ports:
      - "9094:8080"

  # Access Node B

  scorpio-node-b:
    image: scorpiobroker/all-in-one-runner:java-latest
    environment:
      DBHOST: postgis-node-b
    ports:
      - "9091:9090"
    depends_on:
      - postgis-node-b

  postgis-node-b:
    image: postgis/postgis
    ports:
      - "5432"
    environment:
      POSTGRES_USER: ngb
      POSTGRES_PASSWORD: ngb
      POSTGRES_DB: ngb

  desmos-node-b:
    image: desmos-api:latest
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres-node-b:5432/dbtest
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: postgres
      SPRING_FLYWAY_URL: jdbc:postgresql://postgres-node-b:5432/dbtest
      LOGGING_LEVEL_ES_IN2_DESMOS: DEBUG
      CLIENT_ORGANIZATIONID: VATES-S9999999E
      DLT_ADAPTER_PROVIDER: digitelts
      DLT_ADAPTER_INTERNAL_DOMAIN: http://dlt-adapter-node-b:8080
      DLT_ADAPTER_EXTERNAL_DOMAIN: http://dlt-adapter-node-b:8080
      TX_SUBSCRIPTION_NOTIFICATION_ENDPOINT: http://desmos-node-b:8080/api/v1/notifications/dlt
      TX_SUBSCRIPTION_ENTITY_TYPES: ProductOffering,Category,Catalogue
      BROKER_PROVIDER: scorpio
      BROKER_INTERNAL_DOMAIN: http://scorpio-node-b:9090
      BROKER_EXTERNAL_DOMAIN: http://scorpio-node-b:9090
      NGSI_SUBSCRIPTION_NOTIFICATION_ENDPOINT: http://desmos-node-b:8080/api/v1/notifications/broker
      NGSI_SUBSCRIPTION_ENTITY_TYPES: ProductOffering,Category,Catalogue
    ports:
      - "9093:8080"
    depends_on:
      - dlt-adapter-node-b
      - scorpio-node-b
      - postgres-node-b

  postgres-node-b:
    image: postgres:16.1
    ports:
      - "5435:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: dbtest

  dlt-adapter-node-b:
    image: quay.io/digitelts/dlt-adapter:1.4-SNAPSHOT
    environment:
      PRIVATE_KEY: 0x304d170fb355df65cc17ef7934404fe9baee73a1244380076436dec6fafb1e1f
      DOME_EVENTS_CONTRACT_ADDRESS:
      RPC_ADDRESS: http://ganache:8545
      DOME_PRODUCTION_BLOCK_NUMBER: 0
      ISS: 0x9eb763b0a6b7e617d56b85f1df943f176018c8eedb2dd9dd37c0bd77496833fe
    ports:
      - "9095:8080"
