services:

  issuer-keycloak:
    image: in2workspace/issuer-keycloak-plugin:v1.1.0-SNAPSHOT
    volumes:
      - ./imports:/opt/keycloak/data/import
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_URL: http://localhost:8088
      KC_HOSTNAME_ADMIN_URL: http://localhost:8088
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-postgres/cred
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      DB_PORT: 5432
      ISSUER_API_URL: http://issuer-api:8080
      PRE_AUTH_LIFESPAN: 10 # required?
      PRE_AUTH_LIFESPAN_TIME_UNIT: MINUTES # required?
      TX_CODE_SIZE: 4 # required?
      TX_CODE_DESCRIPTION: Enter the PIN code # required?
      TOKEN_EXPIRATION: 2592000 # required?
    ports:
      - "8081:8080"
    links:
      - keycloak-postgres
    networks:
      - local-network

  keycloak-postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: cred
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - local-network

  issuer-ui:
    image: in2workspace/credential-issuer-ui:v1.1.0-SNAPSHOT
    ports:
      - "4201:8088" # 8088?
    networks:
      - local-network

  issuer-api:
    image: in2workspace/issuer-api:v0.5.0-SNAPSHOT
    environment:
      APP_CONFIGS_IAM_EXTERNAL_DOMAIN: http://issuer-keycloak:8080
      APP_CONFIGS_IAM_INTERNAL_DOMAIN: http://issuer-keycloak:8080
      APP_CONFIGS_ISSUER_EXTERNAL_DOMAIN: http://credential-issuer:8071
      APP_CONFIGS_AUTHENTIC_SOURCES_DOMAIN: http://localhost:8072
      APP_CONFIGS_KEY_VAULT_DOMAIN: http://localhost:8081
      APP_CONFIGS_REMOTE_SIGNATURE_DOMAIN: http://host.docker.internal:8050
      APP_CONFIGS_ISSUER_DID: did:key:z6MkqmaCT2JqdUtLeKah7tEVfNXtDXtQyj4yxEgV11Y5CqUa
      APP_CONFIGS_JWT_DECODER_PATH: /realms/CredentialIssuer/protocol/openid-connect/certs
      APP_CONFIGS_JWT_DECODER_LOCAL_PATH: /realms/CredentialIssuer
      APP_CONFIGS_JWT_VALIDATOR: http://localhost:8088/realms/CredentialIssuer
      APP_CONFIGS_PRE_AUTH_CODE_URI_TEMPLATE: /realms/CredentialIssuer/verifiable-credential/{{did}}/credential-offer
      APP_CONFIGS_TOKEN_URI_TEMPLATE: /realms/CredentialIssuer/verifiable-credential/{{did}}/token
      SPRING_MAIL_HOST: host.docker.internal
      SPRING_MAIL_PORT: 1025
      SPRING_MAIL_USERNAME:
      SPRING_MAIL_PASSWORD:
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: false
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: false
      SPRING_R2DBC_URL: r2dbc:postgresql://issuer-postgres:5432/issuer
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: postgres
      SPRING_FLYWAY_URL: jdbc:postgresql://issuer-postgres:5432/issuer
    ports:
      - "8071:8071"
    networks:
      - local-network

  issuer-postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: issuer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data2
    networks:
      - local-network

volumes:
  postgres_data:

networks:
  local-network:
    external: true